name: Inclusive Terminology Linter

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches: [ main ]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  terminology-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: check terminology
        uses: BryanMThomas/inclusive-terminology-workflow@main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  alex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Comment on new PR
      uses: BryanMThomas/inclusive-terminology-workflow@add-alex
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message_id: 'alex'
        no_binary: false
        profanity_sureness: 1
        pr_only: false
        glob_pattern: "services/**"
