name: Inclusive Terminology Linter

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches: [ main ]

jobs:
  terminology:
    runs-on: ubuntu-latest

    steps:
        # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run simple action
        uses: BryanMThomas/javascript-action@v1
        with:
          milliseconds: 2000
      - name: Comment Inclusive Check on new PR
        uses: BryanMThomas/inclusive-terminology-workflow@version-1
        with:
         allFiles: false
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 
