name: Inclusive Terminology Linter

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches: [ main ]

jobs:
  terminology:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Comment on new PR
      uses: BryanMThomas/inclusive-terminology-workflow@version-2
      with:
        message_id: 'Inclusive Check'
        pr_only: true
        glob_pattern: "*"
