name: Inclusive Terminology Linter

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches: [ main ]

jobs:
  terminology:
    runs-on: ubuntu-latest

    steps:
        # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        # Runs Inclusive check and comments on PR
      - name: Comment Inclusive Check on new PR
        uses: BryanMThomas/inclusive-terminology-workflow@version-2
        with:
          message_id: 'Inclusive Check'
          pr_only: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
